version: "3"
services:
  web:
    image: nginx:alpine
    working_dir: "/usr/share/nginx/html"
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
  cli:
    build:
      context: ./cli
      dockerfile: ../Dockerfile
    working_dir: "/opt/wasm"
    volumes:
      - ./cli:/opt/wasm
    entrypoint: ["/usr/bin/env", "sh"]
