version: "3"
services:
  web:
    image: nginx
    working_dir: "/usr/share/nginx/html"
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
  cli:
    image: timbru31/ruby-node:2.7-alpine
    working_dir: "/opt/wasm"
    volumes:
      - ./cli:/opt/wasm
    entrypoint: ["/usr/bin/env", "sh"]
